### PR TITLE
Add support for OAuth token request based on RFC 6749

### PR DESCRIPTION
**Pull request by srinandan**
Add support to send client credentials as a basic auth header, grant type as a form param. This matches RFC 6749.

/edgemicro-auth/token -v -u xxx:xxx -d 'grant_type=client_credentials' -H "Content-Type: application/x-www-form-urlencoded"

The proxy will continue to be backward compatible.

### CODE REVIEW

**Comment by swilliams11** [comment]
I tested this in my Apigee Edge org and it works successfully. 

I noticed that we return two properties with the access token - "token", which was the original value and "access_token".
{
  "token": "eyJraWQiOiIxIiwidHlwIjoi",
  "access_token": "eyJraWQiOiIxIiwid",
  "token_type": "bearer",
  "expires_in": "108000"
}

We should make sure our docs are updated accordingly, and we should communicate the intent behind the change. Does this mean that clients should start using the "access_token" property instead of the "token" property? How long will we support the "token" property? 
https://docs.apigee.com/api-platform/microgateway/2.5.x/cli-reference-edge-microgateway#generate-a-token

We could also handle this new change with "format versioning." A client can include a header, Format-Version: v2 for the new format and receive the response below:
{
  "access_token": "eyJraWQiOiIxIiwid",
  "token_type": "bearer",
  "expires_in": "108000"
}

If the client doesn't include the Format-Version header, then the default response is:
{
  "token": "eyJraWQiOiIxIiwidHlwIjoi",
  "access_token": "eyJraWQiOiIxIiwid",
  "token_type": "bearer",
  "expires_in": "108000"
}


Can you also increment the version in the package.json file?

**Comment by srinandan** [comment]
re: token vs. access_token, I was thinking of support both. Any existing consumers are unaffected by it. Yes, docs need to be updated. 

Based on the recommendation [here](https://cloud.google.com/blog/products/gcp/api-design-which-version-of-versioning-is-right-for-you), we could use the "Accept-Version" header.

yes, i will update package.json once the merge is complete.

**Comment by WWitman** [comment]
I have a few questions re the required doc updates:

1. Does this only affect the /token API? That is, will the "[edgemicro token get](https://docs.apigee.com/api-platform/microgateway/2.5.x/cli-reference-edge-microgateway#generate-a-token)" CLI still work the same?

2. Is this how a user calls the new API:

   /edgemicro-auth/token -v -u xxx:xxx -d 'grant_type=client_credentials' 
     -H "Content-Type: application/x-www-form-urlencoded" -H "Authorization: Basic xxx" 

    where xxx is the Base64(clientId:secret)

3. When you call this API, you get back a "token" and an "access_token", and you can use either to make authenticated API calls. 

4. Will you still be able to use the old /token API and in that case, you just get back a "token". 

5. If you want to just get back an "access_token" you can add this header: -H Format-Version:2 ? 

6. When explaining the intent, do we say that we are supporting sending client credentials as a basic auth header, grant type as a form param, per RFC 6749.

**Comment by srinandan** [comment]
1. It only affects /token. "edgemicro token get" will not be affected by this change.
2. You don't need -u and -H "Authorization...". -u creates the basic auth header. otherwise, you are correct.
3. that is correct. the value to token = access_token. token is non-standard, but retained to be backward compatible.
4. with this proposal, there is no v1 and v2 formats. just one format. the response will contain both token and access_token.

**Pull request merged**
