### PR TITLE
reimplement edgemicro-auth using apigee policies

### PR DESCRIPTION
**Pull request by srinandan**
The new implementation will allow:

1) An easy way to add custom claims, custom expiry etc.
2) Create refresh tokens.
3) Use KVM instead of vault

### CODE REVIEW

**Comment by mdobson** [comment]
@srinandan The only change that you'll want to revert is the deletion of the package.json. We won't be able to distribute if that isn't in there.

**Comment by srinandan** [comment]
But this isn't a node.js project. Why will there be a package.json?

**Comment by mdobson** [comment]
It's distributed via npm.

**Comment by mdobson** [comment]
To be more clear: This is a module published to NPM, and downloaded as a dependency when installing edgemicro. 

I am not sure why it is done this way, but that is how it is currently distributed.

So we'll need to have the package.json in there so I can publish it to NPM, and allow for distribution over NPM.

**Pull request merged**
